/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// <auto-generated />
// Do not modify this file manually
// This file is is updated based on the version found on package.json
[assembly: System.Reflection.AssemblyVersion("2.10.1")]
