name: Build and Test

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        # TODO install all targeted .NET versions then test against all of them
        dotnet-version: 6.0.104
    - name: Restore
      run: dotnet tool restore
    - name: Test
      run: dotnet cake --target Test --configuration Pro --core-only
