name: Pack

on:
  release:
    types: [published]

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.104
    - name: Build
      # MSBuildCommunityTasks doesn't play well with .NET 6 so skip all that
      run: dotnet build --configuration Pro -p:DRBuildMode=coreonly -p:SkipCopyToBuild=true
    - name: Test
      run: dotnet test -p:DRBuildMode=coreonly -p:SkipCopyToBuild=true
    # TODO create GitHub release
    # TODO pack unitypackage using somehting like https://github.com/FatihBAKIR/UnityPacker
