name: Pack

on:
  release:
    types: [published]

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.104
    - name: Restore
      run: dotnet tool restore
    - name: Test
      run: dotnet cake --target Test --configuration Pro --core-only
    # TODO create GitHub release
    # TODO pack unitypackage using somehting like https://github.com/FatihBAKIR/UnityPacker
